"""
Combine the component-model pieces into per-pitch expected run value and pitcher scores.

The combination is a probability-weighted average over the three ways a swing can end:

    E[RV | swing] = P(whiff)   * RV_whiff(count)
                  + P(foul)    * RV_foul(count)
                  + P(in play) * E[RV | contact]

Branch probabilities come from the swing-outcome model (to be trained; see FRAMEWORK.md).
Branch run values come from the tables generated by compute_component_inputs.py.
E[RV | contact] comes from the contact-quality model (to be trained; TaggedHitType values
serve as the interim stand-in until ExitSpeed/Angle are in the dataset).

Working skeleton: the arithmetic here is final, the model hookups are TODO.
"""

import os

import pandas as pd


def load_branch_run_values(inputs_dir, subset="fourseam"):
    """Return a lookup {(balls, strikes, branch): mean run value} from the generated table."""
    path = os.path.join(inputs_dir, "branch_run_values.csv")
    df = pd.read_csv(path)
    df = df[df["subset"] == subset]
    return {
        (int(r["Balls"]), int(r["Strikes"]), r["branch"]): float(r["mean_target"])
        for _, r in df.iterrows()
    }


def expected_run_value_per_swing(p_whiff, p_foul, p_inplay, balls, strikes,
                                 contact_rv, branch_rv):
    """Expected run value of one pitch, conditional on a swing.

    p_whiff, p_foul, p_inplay: swing-outcome model predictions (must sum to ~1)
    contact_rv: contact-quality model prediction for this pitch
    branch_rv: lookup from load_branch_run_values()
    """
    total = p_whiff + p_foul + p_inplay
    if not 0.99 <= total <= 1.01:
        raise ValueError(f"Branch probabilities sum to {total:.4f}, expected 1")
    return (
        p_whiff * branch_rv[(balls, strikes, "whiff")]
        + p_foul * branch_rv[(balls, strikes, "foul")]
        + p_inplay * contact_rv
    )


def score_pitches(df, branch_rv):
    """Attach per-pitch expected run value to a dataframe of swung-at pitches.

    Expects columns: Balls, Strikes, p_whiff, p_foul, p_inplay, contact_rv
    (the p_* and contact_rv columns are the component model predictions).

    TODO: replace with real model predictions once the swing-outcome and
    contact-quality models are trained.
    """
    df = df.copy()
    df["xRV_swing"] = [
        expected_run_value_per_swing(
            r["p_whiff"], r["p_foul"], r["p_inplay"],
            int(r["Balls"]), int(r["Strikes"]),
            r["contact_rv"], branch_rv,
        )
        for _, r in df.iterrows()
    ]
    return df


def pitcher_scores(scored_pitches, min_pitches=100):
    """Aggregate per-pitch expected run value to normalized pitcher scores.

    Averages xRV_swing per pitcher, drops pitchers under the sample threshold, and
    rescales to mean 100, sd 15 across the full qualifying population (lower expected
    run value is better stuff, so better pitchers score above 100).
    """
    g = scored_pitches.groupby("PitcherId")["xRV_swing"].agg(n="size", xrv="mean")
    g = g[g["n"] >= min_pitches]
    mean, sd = g["xrv"].mean(), g["xrv"].std()
    g["stuff_score"] = (100 - (g["xrv"] - mean) * (15 / sd)).round(0).astype(int)
    return g.reset_index()
